IT_SKILLS = [
    "python",
    "java",
    "c",
    "c++",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "html",
    "css",
    "javascript",
    "react",
    "node",
    "django",
    "flask",
    "fastapi",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "data science",
    "pandas",
    "numpy",
    "power bi",
    "tableau",
    "aws",
    "azure",
    "docker",
    "kubernetes",
    "linux",
    "git",
    "github",
    "api",
    "rest api",
    "oop",
    "cloud",
    "devops",
]

PSYCHOLOGY_SKILLS = [
    "clinical psychology",
    "counseling",
    "therapy",
    "psychotherapy",
    "cognitive behavioral therapy",
    "cbt",
    "mental health",
    "psychological assessment",
    "diagnosis",
    "dsm-5",
    "case study",
    "behavioral therapy",
    "group therapy",
    "individual therapy",
    "psychometrics",
    "research methods",
    "qualitative research",
    "quantitative research",
    "clinical internship",
    "patient care",
    "emotional support",
    "stress management",
    "mindfulness",
    "child psychology",
    "family therapy",
    "crisis intervention",
    "mental status examination",
    "cognitive assessment",
    "clinical interview",
    "report writing",
    "ethical practice",
    "psychological testing",
    "psychopathology",
    "psychiatry",
    "substance abuse counseling",
    "social psychology",
    "developmental psychology",
    "neuropsychology",
    "behavior analysis",
    "clinical observation",
    "spss",
    "psychology research",
    "clinical training",
]
